services:
  jira:
    container_name: jira-app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPR_OAU_REGISTR_GITHUB_ID: ${SPR_OAU_REGISTR_GITHUB_ID}
      SPR_OAU_REGISTR_GITHUB_SECRET: ${SPR_OAU_REGISTR_GITHUB_SECRET}
      SPR_OAU_REGISTR_GOOGLE_ID: ${SPR_OAU_REGISTR_GOOGLE_ID}
      SPR_OAU_REGISTR_GOOGLE_SECRET: ${SPR_OAU_REGISTR_GOOGLE_SECRET}
      SPR_MAIL_USERNAME: ${SPR_MAIL_USERNAME}
      SPR_MAIL_PASS: ${SPR_MAIL_PASS}
      SPR_OAU_REGISTR_GITLAB_ID: ${SPR_OAU_REGISTR_GITLAB_ID}
      SPR_OAU_REGISTR_GITLAB_SECRET: ${SPR_OAU_REGISTR_GITLAB_SECRET}
      SPR_DAT_URL: ${SPR_DAT_URL}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_USERNAME_JIRA: ${DATASOURCE_USERNAME_JIRA}
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: postgres_container
    build:
      dockerfile: ./config/Dockerfile
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    ports:
      - "5432:5432"
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  pgdata:
    driver: local